sudo: required
services:
  - docker

before_install:
  - docker build -t krrishkishore/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run krrishkishore/react-test npm test -- --coverage

after_success:
  - docker build -t krrishkishore/multi-client ./client
  - docker build -t krrishkishore/multi-nginx ./nginx
  - docker build -t krrishkishore/multi-server ./server
  - docker build -t krrishkishore/multi-worker ./worker
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin
  - docker push krrishkishore/multi-client
  - docker push krrishkishore/multi-nginx
  - docker push krrishkishore/multi-server
  - docker push krrishkishore/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multi-Docker-env
  bucket_name: elasticbeanstalk-us-east-1-922483402942
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
