sudo: required
services:
  - docker

before_install:
  - docker build -t krrishkishore/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run krrishkishore/react-test npm test -- --coverage

after_success:
  - docker build -t krrishkishore/multi-client ./client
  - docker build -t krrishkishore/multi-nginx ./nginx
  - docker build -t krrishkishore/multi-server ./server
  - docker build -t krrishkishore/multi-worker ./worker
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin
  - docker push krrishkishore/multi-client
  - docker push krrishkishore/multi-nginx
  - docker push krrishkishore/multi-server
  - docker push krrishkishore/multi-worker
